# Generated by Django 3.2.19 on 2023-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
