# Generated by Django 3.2.19 on 2023-06-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_pro_list',
            name='pro_slug',
            field=models.SlugField(null=True),
        ),
    ]
