# Generated by Django 3.2.19 on 2023-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(upload_to='category'),
        ),
    ]
