# Generated by Django 3.2.19 on 2023-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f_product',
            options={'verbose_name': 'f_product', 'verbose_name_plural': 'f_products'},
        ),
        migrations.AlterField(
            model_name='f_product',
            name='pro_img',
            field=models.ImageField(null=True, upload_to='f_products'),
        ),
    ]
