# Generated by Django 3.2.19 on 2023-05-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230519_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f_product',
            options={'verbose_name': 'featured_product', 'verbose_name_plural': 'featured_products'},
        ),
        migrations.AlterField(
            model_name='f_product',
            name='pro_img',
            field=models.ImageField(null=True, upload_to='featured_products'),
        ),
    ]
