# Generated by Django 3.2.19 on 2023-05-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230519_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='f_product',
            new_name='featured_product',
        ),
        migrations.CreateModel(
            name='leatest_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=150)),
                ('pro_desc', models.TextField()),
                ('pro_img', models.ImageField(null=True, upload_to='leatest_products')),
                ('price', models.IntegerField()),
                ('pro_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'verbose_name': 'leatest_products',
                'verbose_name_plural': 'leatest_products',
            },
        ),
    ]
