# Generated by Django 3.2.19 on 2023-05-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230519_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_product',
            name='pro_desc',
            field=models.TextField(),
        ),
    ]
