# Generated by Django 3.2.19 on 2023-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_featured_product_pro_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(upload_to='category_list'),
        ),
    ]
