# Generated by Django 3.2.19 on 2023-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_category_cate_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=350)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField()),
                ('warning_message', models.CharField(max_length=50)),
                ('twitter_link', models.CharField(max_length=250)),
                ('facebook_link', models.CharField(max_length=250)),
                ('linkedln_link', models.CharField(max_length=250)),
                ('instagram_link', models.CharField(max_length=250)),
            ],
        ),
    ]
