# Generated by Django 3.2.19 on 2023-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_footer_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured_product',
            old_name='price',
            new_name='pro_price',
        ),
        migrations.RemoveField(
            model_name='leatest_product',
            name='price',
        ),
        migrations.AddField(
            model_name='featured_product',
            name='pro_colors',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='featured_product',
            name='pro_sizes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='featured_product',
            name='pro_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leatest_product',
            name='pro_colors',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leatest_product',
            name='pro_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leatest_product',
            name='pro_sizes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leatest_product',
            name='pro_stock',
            field=models.IntegerField(null=True),
        ),
    ]
