# Generated by Django 3.2.19 on 2023-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230528_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='featured_product',
            options={'verbose_name': 'featured_product', 'verbose_name_plural': 'featured_products   ( max 12 items )'},
        ),
        migrations.AlterModelOptions(
            name='leatest_product',
            options={'verbose_name': 'leatest_products', 'verbose_name_plural': 'leatest_products  ( max 12 items )'},
        ),
    ]
