# Generated by Django 3.2.19 on 2023-06-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230528_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=550)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Customer login status',
                'verbose_name_plural': 'Customer login status',
            },
        ),
    ]
