# Generated by Django 3.2.19 on 2023-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230613_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_product',
            name='pro_slug',
        ),
        migrations.RemoveField(
            model_name='leatest_product',
            name='pro_slug',
        ),
    ]
