# Generated by Django 3.2.19 on 2023-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230613_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_product',
            name='pro_type',
            field=models.CharField(choices=[('ft', 'featured')], default=(('ft', 'featured'),), max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leatest_product',
            name='pro_type',
            field=models.CharField(choices=[('lt', 'leatest')], default='lt', max_length=50, null=True),
        ),
    ]
