# Generated by Django 3.2.19 on 2023-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pro_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
