# Generated by Django 3.2.19 on 2023-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_pro_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sec_id',
            field=models.IntegerField(null=True),
        ),
    ]
