# Generated by Django 3.2.19 on 2023-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_sec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='trd_id',
            field=models.IntegerField(null=True),
        ),
    ]
