# Generated by Django 3.2.19 on 2023-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_trd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pro_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(null=True),
        ),
    ]
