# Generated by Django 3.2.19 on 2023-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20231009_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pro_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
    ]
